global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'chatbot-backend'
    static_configs:
      - targets: ['backend:5000']
    metrics_path: '/metrics'
    scheme: 'http'